### PR TITLE
Fix bug with duplicate tags allowed

### LINKED ISSUE #153: [PE-D][Tester E] Able to add tags with same name but different case
**Steps to reproduce:<br>**
Execute `add n/tester3 p/91773742 e/john@example.com a/hstreet b/18-02-2000 t/friend t/Friend`

**Expected:<br>**
Both the tags `friend` and `Friend` should be treated as the same.

**Actual:<br>**
The person is added with both tags.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jonasgwt/ped#11

### PR DESCRIPTION
**Pull request by tyw2811**
Closes #153

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -153,6 +153,10 @@ public static Set<Tag> parseTags(Collection<String> tags) throws ParseException
         requireNonNull(tags);
         final Set<Tag> tagSet = new HashSet<>();
         for (String tagName : tags) {
+            if (tagSet.stream().map(t -> t.tagName).anyMatch(t ->
+                    t.equalsIgnoreCase(tagName) && !t.equals(tagName))) {
```
Comment (DanielLimWeiEn) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:157]: Nice parsing the tags to handle different case tags

**Review by DanielLimWeiEn — COMMENTED** [review]
LGTM 🥇
