### PR TITLE
Update UG for Find command and fix bug for parsing multiple prefixes

### LINKED ISSUE #126: [PE-D][Tester E] User is able to `find` using prefixes not mentioned in the UG
**Steps to reproduce:<br>**
Execute the command `find a/John`

**Expected Output:<br>**
A warning message will be shown saying that the `find` command only works for the prefixes as specified in the UG.

**Actual Output:<br>**
The app continues to find (and from my tests it actually works well. Maybe you can update it in the UG)

**Screenshots:<br>**

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jonasgwt/ped#3

### LINKED ISSUE #132: [PE-D][Tester A] UG remind command typo
This is under the "Adding a reminder : remind" section.  
Should be `find n/Betsy`

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CeereeC/ped#6

### LINKED ISSUE #142: [PE-D][Tester E] No prefix provided in the example `find` command in UG
**Actual:<br>**

**Expected:<br>**
There should be a prefix added to the example command. Running `find James Jake` results in error in the app. I believe that it is a UG error and not a functionality bug. 

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jonasgwt/ped#7

### LINKED ISSUE #148: [PE-D][Tester D] User Guide for find command not clear
The specified format is not clear as how find command can be executed for one field or multiple fields. It is also not clear what the [letter] can be. Finding only with the birthday, for example, does not work, but it is not clearly shown in the User Guide.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: asaierika/ped#5

### LINKED ISSUE #156: [PE-D][Tester B] Inconsistent format for 'Locating persons by keyword' section of the user guide
Inconsistency in the format for `find` command.

In user guide:

In application:

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: LikHern/ped#7

### PR DESCRIPTION
**Pull request by edricyeo**
Fix bugs such that a parse exception is thrown when multiple prefixes are inputted.

Updated UG to only allow one prefix to be passed into the `find` command.
Closes #148 

Updated UG to include all valid prefixes for the `find` command.
Closes #126
Closes #142 
Closes #156 

Fixed typo under the "Adding a reminder" section of UG.
Closes #132

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -124,5 +132,21 @@ public static String[] parseBirthdayArray(String[] birthdayInput) throws ParseEx
...
+     */
+    public static void checkMultiplePrefix(ArgumentMultimap argMultimap) throws ParseException {
+        int prefixCount = 0;
+        for (Prefix pfx : validPrefixArray) {
+            if (argMultimap.getValue(pfx).isPresent()) {
+                prefixCount++;
+            }
+        }
+        if (prefixCount > 1) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, MESSAGE_MULTIPLE_PREFIX));
```
Comment (DanielLimWeiEn) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:147]: Nice using exceptions to handle invalid multiple prefixes 👍

**Review by DanielLimWeiEn — COMMENTED** [review]
LGTM 💯
